# Generated by Django 2.2.6 on 2019-10-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_read_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
